"""Canonical PCS v0.1 artifact registry entries."""

from __future__ import annotations

from typing import Any

_CONSUMER_REPOS: dict[str, list[str]] = {
    "AssumptionSet.v0": ["LabTrust-Gym"],
    "SourceSpan.v0": ["LabTrust-Gym"],
    "ClaimArtifact.v0": ["LabTrust-Gym"],
    "RuntimeReceipt.v0": ["LabTrust-Gym"],
    "TraceCertificate.v0": ["CertifyEdge"],
    "EvidenceBundle.v0": ["LabTrust-Gym"],
    "ScienceClaimBundle.v0": ["LabTrust-Gym"],
    "VerificationResult.v0": ["Provability Fabric"],
    "SignedScienceClaimBundle.v0": ["Provability Fabric"],
    "ReleaseManifest.v0": ["pcs-core"],
    "HandoffManifest.v0": ["pcs-core"],
    "ReleaseChainValidationResult.v0": ["pcs-core", "Scientific Memory"],
    "ArtifactRegistry.v0": ["pcs-core"],
}

_REGISTRY_ENTRIES: dict[str, dict[str, Any]] = {
    "AssumptionSet.v0": {
        "artifact_type": "AssumptionSet.v0",
        "schema": "schemas/AssumptionSet.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": ["Draft", "HumanReviewed", "RuntimeObserved", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "assumption_set_id",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": ["source_commit_not_placeholder"],
    },
    "SourceSpan.v0": {
        "artifact_type": "SourceSpan.v0",
        "schema": "schemas/SourceSpan.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": ["Draft", "Extracted", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "source_span_id",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": ["source_commit_not_placeholder"],
    },
    "ClaimArtifact.v0": {
        "artifact_type": "ClaimArtifact.v0",
        "schema": "schemas/ClaimArtifact.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": [
            "Draft",
            "RuntimeObserved",
            "CertificateChecked",
            "ProofChecked",
            "Rejected",
            "Stale",
        ],
        "required_release_fields": [
            "schema_version",
            "artifact_id",
            "assumption_set_ref",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": ["assumption_set_ref_present"],
    },
    "RuntimeReceipt.v0": {
        "artifact_type": "RuntimeReceipt.v0",
        "schema": "schemas/RuntimeReceipt.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": ["RuntimeObserved", "RuntimeChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "receipt_id",
            "trace_hash",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "trace_hash_present",
            "source_commit_matches_release_manifest",
        ],
    },
    "TraceCertificate.v0": {
        "artifact_type": "TraceCertificate.v0",
        "schema": "schemas/TraceCertificate.v0.schema.json",
        "producer": "CertifyEdge",
        "allowed_statuses": ["CertificatePending", "CertificateChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "certificate_id",
            "trace_hash",
            "spec_hash",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "trace_hash_matches_runtime_receipt",
            "status_is_certificate_checked_for_release",
            "source_commit_matches_release_manifest",
        ],
    },
    "EvidenceBundle.v0": {
        "artifact_type": "EvidenceBundle.v0",
        "schema": "schemas/EvidenceBundle.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": ["Draft", "CertificateChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "bundle_id",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": ["certificate_refs_resolve"],
    },
    "ScienceClaimBundle.v0": {
        "artifact_type": "ScienceClaimBundle.v0",
        "schema": "schemas/ScienceClaimBundle.v0.schema.json",
        "producer": "LabTrust-Gym",
        "allowed_statuses": [
            "Draft",
            "RuntimeObserved",
            "CertificateChecked",
            "ProofChecked",
            "Rejected",
            "Stale",
        ],
        "required_release_fields": [
            "schema_version",
            "bundle_id",
            "assumption_set",
            "runtime_receipts",
            "status",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "non_empty_runtime_receipts",
            "certified_bundle_has_certificate_when_checked",
        ],
    },
    "VerificationResult.v0": {
        "artifact_type": "VerificationResult.v0",
        "schema": "schemas/VerificationResult.v0.schema.json",
        "producer": "Provability Fabric",
        "allowed_statuses": ["ProofChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "verification_id",
            "status",
            "verified_input",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "verified_input_bundle_hash_matches_certified",
            "failed_checks_block_import_ready_status",
        ],
    },
    "SignedScienceClaimBundle.v0": {
        "artifact_type": "SignedScienceClaimBundle.v0",
        "schema": "schemas/SignedScienceClaimBundle.v0.schema.json",
        "producer": "Provability Fabric",
        "allowed_statuses": ["ProofChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "signed_bundle_id",
            "signed_input_bundle_hash",
            "science_claim_bundle",
            "verification_result",
            "source_repo",
            "source_commit",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "signed_input_bundle_hash_matches_certified",
            "embedded_bundle_passes_science_claim_semantics",
        ],
    },
    "ReleaseManifest.v0": {
        "artifact_type": "ReleaseManifest.v0",
        "schema": "schemas/ReleaseManifest.v0.schema.json",
        "producer": "pcs-core",
        "allowed_statuses": ["Draft", "Validated", "Rejected", "Stale", "Deprecated"],
        "required_release_fields": [
            "schema_version",
            "release_id",
            "release_candidate",
            "validation_profile",
            "producer_repos",
            "artifacts",
            "release_status",
            "chain_root",
            "release_chain_validation_result",
            "canonical_signed_bundle",
            "canonical_claim_id",
            "limitations_notice",
            "signature_or_digest",
        ],
        "semantic_checks": [
            "release_mode_commit_policy",
            "artifact_hashes_match_files",
        ],
    },
    "HandoffManifest.v0": {
        "artifact_type": "HandoffManifest.v0",
        "schema": "schemas/HandoffManifest.v0.schema.json",
        "producer": "pcs-core",
        "allowed_statuses": ["Draft", "Validated", "Rejected", "Stale", "Deprecated"],
        "required_release_fields": [
            "schema_version",
            "handoff_id",
            "handoff_kind",
            "input_artifacts",
            "expected_outputs",
            "invariants",
            "status",
            "signature_or_digest",
        ],
        "semantic_checks": ["handoff_input_hashes_when_validated"],
    },
    "ComponentReleaseFragment.v0": {
        "artifact_type": "ComponentReleaseFragment.v0",
        "schema": "schemas/ComponentReleaseFragment.v0.schema.json",
        "producer": "pcs-core",
        "allowed_statuses": ["Draft", "Validated", "Rejected", "Stale", "Deprecated"],
        "required_release_fields": [
            "schema_version",
            "component",
            "source_repo",
            "source_commit",
            "artifacts",
            "signature_or_digest",
        ],
        "semantic_checks": [],
    },
    "ReleaseChainValidationResult.v0": {
        "artifact_type": "ReleaseChainValidationResult.v0",
        "schema": "schemas/ReleaseChainValidationResult.v0.schema.json",
        "producer": "pcs-core",
        "allowed_statuses": ["ProofChecked", "Rejected", "Stale"],
        "required_release_fields": [
            "schema_version",
            "validation_id",
            "release_id",
            "status",
            "checks",
            "artifacts_checked",
            "failure_codes",
            "signature_or_digest",
        ],
        "semantic_checks": ["status_matches_check_outcomes"],
    },
    "ArtifactRegistry.v0": {
        "artifact_type": "ArtifactRegistry.v0",
        "schema": "schemas/ArtifactRegistry.v0.schema.json",
        "producer": "pcs-core",
        "allowed_statuses": ["Draft", "Validated", "Deprecated"],
        "required_release_fields": [
            "schema_version",
            "registry_id",
            "registry_version",
            "entries",
            "signature_or_digest",
        ],
        "semantic_checks": ["entries_cover_required_artifact_types"],
    },
}


def registry_entries() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for key, value in _REGISTRY_ENTRIES.items():
        entry = dict(value)
        entry.setdefault("consumer_repos", _CONSUMER_REPOS.get(key, [entry["producer"]]))
        entry.setdefault("canonical_hash_required", True)
        entry.setdefault("release_mode_required", key not in {"ArtifactRegistry.v0"})
        out[key] = entry
    return out
